# Generated by Django 4.1 on 2022-09-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.JSONField(default=list),
        ),
    ]
